apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: myapp
  namespace: sample-namespace
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myapp
status:
  loadBalancer: {}
