apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-helm-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: 15.1.0   # version of the Helm chart
    helm:
      values: |
        service:
          type: ClusterIP
          port: 80
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}   # enables auto-sync
